[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "FiSGO"
authors = [{name = "Gerard Gonzalo Calbeto", email = "ggonzalo.math@gmail.com"}]
dynamic = ["version", "description"]
readme = "README.md"